#!/bin/bash

print_usage () {
    echo "Create certificates for wificonfigurator"
    echo
    echo "Checks path /etc/wificonfigurator/ca.crt and /etc/wificonfigurator/ca.key"
    echo "If the files don't exist, creates self signed certificates."
}

if [[ $1 == "--help" ]] || [[ $1 == "-h" ]]; then
    print_usage
    exit 0
fi

PASSFILE=/tmp/wificonfigpass.txt
FILENAME=uiwificonfigurator
ROOTPATH=/etc/wificonfigurator.d/
FILEPATH=${ROOTPATH}${FILENAME}

if ! test -f ${FILEPATH}key.pem; then
    mkdir -p ${ROOTPATH}

    openssl req -x509 -newkey rsa:4096 -nodes -out ${ROOTPATH}cert.pem -keyout ${ROOTPATH}key.pem -days 365000\
    -subj "/C=UK/O=wificonf/OU=Domain Control Validated/CN=uiwificonfigurator.org"

fi
