#!/bin/bash

INTERFACE=$1
SERVICE=wpa_supplicant@${INTERFACE}.service
echo "${0} ${SERVICE}"
sleep 2

systemctl enable ${SERVICE}
systemctl start ${SERVICE}
systemctl restart ${SERVICE}
echo "restarting ${SERVICE}"
sleep 10
ping -c 2 google.com

if [ $? -eq 0 ]; then
    touch /etc/wificonfigurator.done
    exit 0
fi

systemctl disable ${SERVICE}
systemctl stop ${SERVICE}

systemctl restart wificonfigurator-accesspoint.service
systemctl restart wificonfigurator-webui.service

exit 1